geotrek/sensitivity/urls.py
from django.conf import settings
from django.conf.urls import url

from mapentity.registry import registry

from geotrek.common.urls import PublishableEntityOptions

from . import models
from . import serializers
from . import views


class SensitiveAreaEntityOptions(PublishableEntityOptions):
    def get_serializer(self):
        return serializers.SensitiveAreaSerializer

    def get_queryset(self):
        return self.model.objects.existing()


urlpatterns = [
    url(r'^api/(?P<lang>\w\w)/sensitiveareas/(?P<pk>\d+).kml$',
        views.SensitiveAreaKMLDetail.as_view(), name="sensitivearea_kml_detail"),
]
if 'geotrek.trekking' in settings.INSTALLED_APPS:
    urlpatterns.append(url(r'^api/(?P<lang>\w\w)/treks/(?P<pk>\d+)/sensitiveareas\.geojson$',
                           views.TrekSensitiveAreaViewSet.as_view({'get': 'list'}),
                           name="trek_sensitivearea_geojson"))
urlpatterns += registry.register(models.SensitiveArea, SensitiveAreaEntityOptions)

geotrek/urls.py
from django.conf import settings
from django.conf.urls import include, url, static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.contrib.auth import views as auth_views

from mapentity.forms import AttachmentForm

from geotrek.common import views as common_views

from paperclip import views as paperclip_views

handler403 = 'mapentity.views.handler403'
handler404 = 'mapentity.views.handler404'


urlpatterns = [
    url(r'^$', common_views.home, name='home'),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': settings.ROOT_URL + '/'}, name='logout',),

    url(r'', include('geotrek.common.urls', namespace='common', app_name='common')),
    url(r'', include('geotrek.altimetry.urls', namespace='altimetry', app_name='altimetry')),

    url(r'', include('mapentity.urls', namespace='mapentity', app_name='mapentity')),
    url(r'^paperclip/add-for/(?P<app_label>[\w\-]+)/(?P<model_name>[\w\-]+)/(?P<pk>\d+)/$',
        paperclip_views.add_attachment, kwargs={'attachment_form': AttachmentForm}, name="add_attachment"),
    url(r'^paperclip/update/(?P<attachment_pk>\d+)/$', paperclip_views.update_attachment,
        kwargs={'attachment_form': AttachmentForm}, name="update_attachment"),
    url(r'^paperclip/', include('paperclip.urls')),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

if 'geotrek.core' in settings.INSTALLED_APPS:
    urlpatterns.append(url(r'', include('geotrek.core.urls', namespace='core', app_name='core')))
if 'geotrek.land' in settings.INSTALLED_APPS:
    urlpatterns.append(url(r'', include('geotrek.land.urls', namespace='land', app_name='land')))
if 'geotrek.zoning' in settings.INSTALLED_APPS:
    urlpatterns.append(url(r'', include('geotrek.zoning.urls', namespace='zoning', app_name='zoning')))
if 'geotrek.infrastructure' in settings.INSTALLED_APPS:
    urlpatterns.append(url(r'', include('geotrek.infrastructure.urls', namespace='infrastructure', app_name='infrastructure')))
if 'geotrek.maintenance' in settings.INSTALLED_APPS:
    urlpatterns.append(url(r'', include('geotrek.maintenance.urls', namespace='maintenance', app_name='maintenance')))
if 'geotrek.trekking' in settings.INSTALLED_APPS:
    urlpatterns.append(url(r'', include('geotrek.trekking.urls', namespace='trekking', app_name='trekking')))
if 'geotrek.tourism' in settings.INSTALLED_APPS:
    urlpatterns.append(url(r'', include('geotrek.tourism.urls', namespace='tourism', app_name='tourism')))
if 'geotrek.flatpages' in settings.INSTALLED_APPS:
    urlpatterns.append(url(r'', include('geotrek.flatpages.urls', namespace='flatpages', app_name='flatpages')))
if 'geotrek.feedback' in settings.INSTALLED_APPS:
    urlpatterns.append(url(r'', include('geotrek.feedback.urls', namespace='feedback', app_name='feedback')))
if 'geotrek.sensitivity' in settings.INSTALLED_APPS:
    urlpatterns.append(url(r'', include('geotrek.sensitivity.urls', namespace='sensitivity', app_name='sensitivity')))
if 'geotrek.api' in settings.INSTALLED_APPS:
    urlpatterns.append(url(r'^api/v2/', include('geotrek.api.v2.urls', namespace='apiv2', app_name='apiv2')))

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG and settings.DEBUG_TOOLBAR:
    try:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns
    except ImportError:
        pass

geotrek/sensitivity/models.py
"""
   Sensitivity models
"""

import datetime
import simplekml

from django.conf import settings
from django.contrib.gis.db import models
from django.utils.translation import pgettext_lazy, ugettext_lazy as _
from mapentity.models import MapEntityMixin
from mapentity.serializers import plain_text
from geotrek.authent.models import StructureRelated
from geotrek.common.mixins import (OptionalPictogramMixin, NoDeleteMixin, TimeStampedModelMixin, AddPropertyMixin)
from geotrek.common.utils import intersecting, classproperty


class SportPractice(models.Model):
    name = models.CharField(max_length=250, db_column='nom', verbose_name=_(u"Name"))

    class Meta:
        ordering = ['name']
        db_table = 's_b_pratique_sportive'
        verbose_name = _(u"Sport practice")
        verbose_name_plural = _(u"Sport practices")

    def __unicode__(self):
        return self.name


class Species(OptionalPictogramMixin):
    SPECIES = 1
    REGULATORY = 2

    name = models.CharField(max_length=250, db_column='nom', verbose_name=_(u"Name"))
    period01 = models.BooleanField(default=False, db_column='periode01', verbose_name=_(u"January"))
    period02 = models.BooleanField(default=False, db_column='periode02', verbose_name=_(u"February"))
    period03 = models.BooleanField(default=False, db_column='periode03', verbose_name=_(u"March"))
    period04 = models.BooleanField(default=False, db_column='periode04', verbose_name=_(u"April"))
    period05 = models.BooleanField(default=False, db_column='periode05', verbose_name=_(u"May"))
    period06 = models.BooleanField(default=False, db_column='periode06', verbose_name=_(u"June"))
    period07 = models.BooleanField(default=False, db_column='periode07', verbose_name=_(u"July"))
    period08 = models.BooleanField(default=False, db_column='periode08', verbose_name=_(u"August"))
    period09 = models.BooleanField(default=False, db_column='periode09', verbose_name=_(u"September"))
    period10 = models.BooleanField(default=False, db_column='periode10', verbose_name=_(u"October"))
    period11 = models.BooleanField(default=False, db_column='periode11', verbose_name=_(u"November"))
    period12 = models.BooleanField(default=False, db_column='periode12', verbose_name=_(u"Decembre"))
    practices = models.ManyToManyField(SportPractice, db_table='s_r_espece_pratique_sportive',
                                       verbose_name=_(u"Sport practices"))
    url = models.URLField(blank=True, verbose_name="URL")
    radius = models.IntegerField(db_column='rayon', blank=True, null=True, verbose_name=_(u"Bubble radius"),
                                 help_text=_(u"meters"))
    category = models.IntegerField(verbose_name=_(u"Category"), db_column='categorie', editable=False, default=SPECIES,
                                   choices=((SPECIES, pgettext_lazy(u"Singular", u"Species")),
                                            (REGULATORY, _(u"Regulatory"))))
    eid = models.CharField(verbose_name=_(u"External id"), max_length=128, blank=True, null=True,
                           db_column='id_externe')

    class Meta:
        ordering = ['name']
        db_table = 's_b_espece_ou_suite_zone_regl'
        verbose_name = pgettext_lazy(u"Singular", u"Species")
        verbose_name_plural = _(u"Species")

    def __unicode__(self):
        return self.name

    def pretty_period(self):
        return u", ".join([unicode(self._meta.get_field('period{:02}'.format(p)).verbose_name)
                           for p in range(1, 13)
                           if getattr(self, 'period{:02}'.format(p))])

    def pretty_practices(self):
        return u", ".join([unicode(practice) for practice in self.practices.all()])


class SensitiveArea(MapEntityMixin, StructureRelated, TimeStampedModelMixin, NoDeleteMixin,
                    AddPropertyMixin):
    geom = models.GeometryField(srid=settings.SRID)
    species = models.ForeignKey(Species, verbose_name=_(u"Sensitive area"), db_column='espece',
                                on_delete=models.PROTECT)
    published = models.BooleanField(verbose_name=_(u"Published"), default=False,
                                    help_text=_(u"Online"), db_column='public')
    publication_date = models.DateField(verbose_name=_(u"Publication date"),
                                        null=True, blank=True, editable=False,
                                        db_column='date_publication')
    description = models.TextField(verbose_name=_("Description"), blank=True)
    contact = models.TextField(verbose_name=_("Contact"), blank=True)
    eid = models.CharField(verbose_name=_(u"External id"), max_length=128, blank=True, null=True,
                           db_column='id_externe')

    objects = NoDeleteMixin.get_manager_cls(models.GeoManager)()

    class Meta:
        db_table = 's_t_zone_sensible'
        verbose_name = _(u"Sensitive area")
        verbose_name_plural = _(u"Sensitive areas")
        permissions = (
            ("import_sensitivearea", "Can import Sensitive area"),
        )

    def __unicode__(self):
        return self.species.name

    @property
    def radius(self):
        if self.species.radius is None:
            return settings.SENSITIVITY_DEFAULT_RADIUS
        return self.species.radius

    @classproperty
    def radius_verbose_name(cls):
        return _("Radius")

    @property
    def category_display(self):
        return self.species.get_category_display()

    @classproperty
    def category_verbose_name(cls):
        return _("Category")

    def save(self, *args, **kwargs):
        if self.publication_date is None and self.published:
            self.publication_date = datetime.date.today()
        if self.publication_date is not None and not self.published:
            self.publication_date = None
        super(SensitiveArea, self).save(*args, **kwargs)

    @property
    def any_published(self):
        return self.published

    @property
    def published_status(self):
        """Returns the publication status by language.
        """
        status = []
        for l in settings.MAPENTITY_CONFIG['TRANSLATED_LANGUAGES']:
            status.append({
                'lang': l[0],
                'language': l[1],
                'status': self.published
            })
        return status

    @property
    def published_langs(self):
        """Returns languages in which the object is published.
        """
        if self.published:
            return [l[0] for l in settings.MAPENTITY_CONFIG['TRANSLATED_LANGUAGES']]
        else:
            return []

    @property
    def species_display(self):
        s = u'<a data-pk="%s" href="%s" title="%s">%s</a>' % (self.pk,
                                                              self.get_detail_url(),
                                                              self.species.name,
                                                              self.species.name)
        if self.published:
            s = u'<span class="badge badge-success" title="%s">&#x2606;</span> ' % _("Published") + s
        return s

    @property
    def extent(self):
        return self.geom.transform(settings.API_SRID, clone=True).extent if self.geom else None

    def kml(self):
        """Exports sensitivearea into KML format"""
        kml = simplekml.Kml()
        geom = self.geom
        if geom.geom_type == 'Point':
            geom = geom.buffer(self.species.radius or settings.SENSITIVITY_DEFAULT_RADIUS, 4)
        geom = geom.transform(4326, clone=True)  # KML uses WGS84
        line = kml.newpolygon(name=self.species.name,
                              description=plain_text(self.description),
                              outerboundaryis=geom.coords[0])
        line.style.linestyle.color = simplekml.Color.red  # Red
        line.style.linestyle.width = 4  # pixels
        return kml.kml()

    def is_public(self):
        return self.published

    @property
    def pretty_period(self):
        return self.species.pretty_period()
    pretty_period_verbose_name = _("Period")

    @property
    def pretty_practices(self):
        return self.species.pretty_practices()
    pretty_practices_verbose_name = _("Practices")


if 'geotrek.core' in settings.INSTALLED_APPS:
    from geotrek.core.models import Topology
    Topology.add_property('sensitive_areas', lambda self: intersecting(SensitiveArea, self, settings.SENSITIVE_AREA_INTERSECTION_MARGIN), _(u"Sensitive areas"))
    Topology.add_property('published_sensitive_areas', lambda self: intersecting(SensitiveArea, self, settings.SENSITIVE_AREA_INTERSECTION_MARGIN).filter(published=True), _(u"Published sensitive areas"))

geotrek/api/v2/views/sensitivity.py
from __future__ import unicode_literals

from django.conf import settings
from django.db.models import F, Case, When
from django_filters.rest_framework.backends import DjangoFilterBackend
from rest_framework.permissions import IsAuthenticatedOrReadOnly

from geotrek.api.v2 import serializers as api_serializers, \
    viewsets as api_viewsets
from geotrek.api.v2.functions import Transform, Buffer, GeometryType, Area
from geotrek.sensitivity import models as sensitivity_models
from ..filters import GeotrekQueryParamsFilter, GeotrekInBBoxFilter, GeotrekSensitiveAreaFilter


class SensitiveAreaViewSet(api_viewsets.GeotrekViewset):
    filter_backends = (
        DjangoFilterBackend,
        GeotrekQueryParamsFilter,
        GeotrekInBBoxFilter,
        GeotrekSensitiveAreaFilter,
    )
    permission_classes = [IsAuthenticatedOrReadOnly]
    authentication_classes = []
    bbox_filter_field = 'geom2d_transformed'
    bbox_filter_include_overlapping = True

    def get_serializer_class(self):
        if 'bubble' in self.request.GET:
            base_serializer_class = api_serializers.BubbleSensitiveAreaListSerializer
        else:
            base_serializer_class = api_serializers.SensitiveAreaListSerializer
        format_output = self.request.query_params.get('format', 'json')
        dimension = self.request.query_params.get('dim', '2')
        return api_serializers.override_serializer(format_output, dimension, base_serializer_class)

    def get_queryset(self):
        queryset = sensitivity_models.SensitiveArea.objects.existing() \
            .filter(published=True) \
            .select_related('species', 'structure') \
            .prefetch_related('species__practices') \
            .annotate(geom_type=GeometryType(F('geom'))) \
            .order_by('pk')  # Required for reliable pagination
        if 'bubble' in self.request.GET:
            queryset = queryset.annotate(geom2d_transformed=Transform(F('geom'), settings.API_SRID))
        else:
            queryset = queryset.annotate(geom2d_transformed=Case(
                When(geom_type='POINT', then=Transform(Buffer(F('geom'), F('species__radius'), 4), settings.API_SRID)),
                When(geom_type='POLYGON', then=Transform(F('geom'), settings.API_SRID))
            ))
        # Ensure smaller areas are at the end of the list, ie above bigger areas on the map
        # to ensure we can select every area in case of overlapping
        queryset = queryset.annotate(area=Area('geom2d_transformed')).order_by('-area')
        return queryset

    def list(self, request, *args, **kwargs):
        response = super(SensitiveAreaViewSet, self).list(request, *args, **kwargs)
        response['Access-Control-Allow-Origin'] = '*'
        return response


class SportPracticeViewSet(api_viewsets.GeotrekViewset):
    filter_backends = (
        DjangoFilterBackend,
        GeotrekQueryParamsFilter,
    )
    permission_classes = [IsAuthenticatedOrReadOnly]
    serializer_class = api_serializers.SportPracticeListSerializer
    serializer_detail_class = api_serializers.SportPracticeListSerializer
    authentication_classes = []

    def get_queryset(self):
        queryset = sensitivity_models.SportPractice.objects.all()
        queryset = queryset.order_by('pk')  # Required for reliable pagination
        return queryset

    def list(self, request, *args, **kwargs):
        response = super(SportPracticeViewSet, self).list(request, *args, **kwargs)
        response['Access-Control-Allow-Origin'] = '*'
        return response

geotrek/sensitivity/templates/sensitivity/sensitivearea_detail.html
{% extends "mapentity/mapentity_detail.html" %}


{% block mappanel %}
    {% if object.get_geom %}
        {% load i18n static mapentity_tags leaflet_tags geojson_tags %}
        <div id="detailmap"
             data-fitmaxzoom="{{ MAP_FIT_MAX_ZOOM }}"
             data-mapextent="{{ object|latlngbounds }}"
             data-readonly="{% if readonly %}readonly{% endif %}">
            <script type="application/json" class="geojsonfeature">
                {{ object|geojsonfeature:"radius"|safe }}
            </script>
        </div>
        {% leaflet_map "detailmap" fitextent=False creatediv=False %}
    {% else %}
        <p class="nomap">{{ empty_map_message }}</p>
    {% endif %}
{% endblock mappanel %}


{% block extrabody %}
    {{ block.super }}
    <script type="text/javascript">
    console.log("ici1");
    L.ObjectsLayer.pointToLayer = function (geojson, latlng) {
        console.log("ici2")
        return new L.Circle(latlng, {{ object.species.radius }});
    };
    </script>
{% endblock extrabody %}

geotrek/sensitivity/templates/sensitivity/sensitivearea_detail_attributes.html
{% extends "mapentity/mapentity_detail_attributes.html" %}
{% load i18n mapentity_tags %}


{% block attributes %}

    <h3>{% trans "Attributes" %}</h3>
    <table class="table-striped table-bordered table">
        {% if sensitivearea.species.category == 2 %}
            <tr>
                <th>{{ sensitivearea.species|verbose:"name" }}</th>
                <td>{{ sensitivearea.species.name }}</td>
            </tr>
        {% else %}
            <tr>
                <th>{{ sensitivearea|verbose:"species" }}</th>
                <td>{{ sensitivearea.species }}</td>
            </tr>
        {% endif %}
        <tr>
            <th>{% trans "Period" %}</th>
            <td>{{ sensitivearea.species.pretty_period }}</td>
        </tr>
        <tr>
            <th>{{ sensitivearea.species|verbose:"practices" }}</th>
            <td>{{ sensitivearea.species.pretty_practices }}</td>
        </tr>
        <tr>
            <th>{{ sensitivearea.species|verbose:"url" }}</th>
            <td><a href="{{ sensitivearea.species.url }}" target="_blank">{{ sensitivearea.species.url }}</a></td>
        </tr>
        {% if sensitivearea.species.radius != None %}
            <tr>
                <th>{{ sensitivearea.species|verbose:"radius" }}</th>
                <td>{{ sensitivearea.species.radius }} m</td>
            </tr>
        {% endif %}
        <tr>
            <th>{{ sensitivearea|verbose:"description" }}</th>
            <td>{{ sensitivearea.description|safe }}</td>
        </tr>
        <tr>
            <th>{{ sensitivearea|verbose:"contact" }}</th>
            <td>{{ sensitivearea.contact|safe }}</td>
        </tr>
        <tr>
            <th>{{ sensitivearea|verbose:"structure" }}</th>
            <td>{{ sensitivearea.structure }}</td>
        </tr>
        {% include "common/publication_info_fragment.html" %}
        {% include "mapentity/trackinfo_fragment.html" %}
    </table>

    {{ block.super }}
{% endblock attributes %}

geotrek/sensitivity/templates/sensitivity/sensitivearea_form.html
{% extends "mapentity/mapentity_form.html" %}

{% load i18n crispy_forms_tags staticfiles %}


{% block extrabody %}
    {{ block.super }}
    <script type="text/javascript">
        var sensitiveareaRadii = JSON.parse('{{ radii|safe }}');
        var sensitiveareaCurrentFeature = null;
        var sensitiveareaCurrentRadius;
        if ($('#id_species').val()) {
            sensitiveareaCurrentRadius = sensitiveareaRadii[$('#id_species').val()];
        } else {
            sensitiveareaCurrentRadius = 50;
        }

        $("#id_species").change(function() {
            sensitiveareaCurrentRadius = sensitiveareaRadii[$(this).val()];
            if (sensitiveareaCurrentFeature && sensitiveareaCurrentFeature.setRadius) {
                sensitiveareaCurrentFeature.setRadius(sensitiveareaCurrentRadius);
            }
        });

        polygonGeometryField = MapEntity.GeometryField.extend({
            _controlDrawOptions: function () {
                return {
                    edit: {
                        featureGroup: this.drawnItems
                    },
                    draw: {
                        circlemarker: false,
                        polyline: false,
                        rectangle: false,
                        circle: false,
                        marker: false
                    }
                };
            }

        });

        bubbleGeometryField = MapEntity.GeometryField.extend({
            load: function() {
                self = this;
                this._map.on('draw:created', function (e) {
                    if (e.layer.setRadius) {
                        e.layer.setRadius(sensitiveareaCurrentRadius);
                    }
                    sensitiveareaCurrentFeature = e.layer;
                });
                var value = (this.store.formfield.value || '');
                if (/^\s*$/.test(value)) {
                    return null;
                }
                var geometry = L.GeoJSON.geometryToLayer(JSON.parse(value), function (geojson, latlng) {
                    if (geojson.type === "Point") {
                        sensitiveareaCurrentFeature = new L.Circle(latlng, sensitiveareaCurrentRadius);
                        return sensitiveareaCurrentFeature;
                    }
                    return new L.CircleMarker(latlng);
                });
                if (geometry) {
                    // Add initial geometry to the map
                    geometry.addTo(this._map);
                    this.drawnItems.addLayer(geometry);
                }
                this._setView();
                return geometry;
            },
            _controlDrawOptions: function () {
                return {
                    edit: {
                        featureGroup: this.drawnItems
                    },
                    draw: {
                        circlemarker: {radius: function() { return sensitiveareaCurrentRadius; }},
                        polyline: false,
                        rectangle: false,
                        circle: false,
                        marker: false
                    }
                };
            }
        });
    </script>
{% endblock extrabody %}

geotrek/sensitivity/templates/sensitivity/sensitivearea_list.html
{% extends "mapentity/mapentity_list.html" %}
{% load i18n staticfiles %}


{% block mainactions %}
    {% if can_add %}
        <a class="btn btn-success" href="{{ model.get_add_url }}?category=1"><i class="icon-plus icon-white"></i> {% trans "Add a sensitive area (Species)" %}</a>
        <a class="btn btn-success" href="{{ model.get_add_url }}?category=2"><i class="icon-plus icon-white"></i> {% trans "Add a sensitive area (Regulatory)" %}</a>
    {% else %}
        <span class="btn disabled" href="#"><i class="icon-plus icon-white"></i> {% trans "Add a sensitive area (Species)" %}</span>
        <span class="btn disabled" href="#"><i class="icon-plus icon-white"></i> {% trans "Add a sensitive area (Regulatory)" %}</span>
    {% endif %}
{% endblock mainactions %}

geotrek/sensitivity/templates/sensitivity/sensitivity_extrabody_fragment.html
{% load i18n %}

<script type="text/javascript">
    MapEntity.i18n['Sensitivity'] = "{% trans "Sensitivity" %}";
    MapEntity.i18n['sensitivearea'] = "{% trans "Sensitive area" %}";
    window.SETTINGS.urls['sensitivearea_layer'] = "{% url "sensitivity:sensitivearea_layer" %}";
</script>

geotrek/sensitivity/templates/sensitivity/sensitivity_extrajs_fragment.html
{% load static %}

<script type="text/javascript" src="{% static "sensitivity/main.js" %}"></script>